17 icons overview
ifahrentholz/eds-editorial pull request #40
Opened 2024-02-21 18:23 UTC by LoomingEcho

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #17 

Test URLs:

- Before: https://develop--eds-editorial--ifahrentholz.hlx.live/
- After: https://17-icons-overview--eds-editorial--ifahrentholz.hlx.live/

2024-02-26 08:01 UTC, samuelecalamita commented on src/blocks/icon-overview/icon-overview.ts
> +    <div class="icon-container">
renderIcon sollte teil des icon-components sein und ohne div icon-container

2024-02-26 08:06 UTC, samuelecalamita commented on src/blocks/icon-overview/icon-overview.ts
> +const getMessage = (block: HTMLElement) => {
getToastMessage wäre bessere denke ich

2024-02-26 08:12 UTC, samuelecalamita commented on src/components/toast.ts
> +  message: string = 'Toast default message';
Please provide a message to display in the toast.

2024-02-26 08:14 UTC, samuelecalamita commented on src/components/toast.ts
> +  duration: number = 10;
default würde ich 3000 machen

2024-02-26 08:14 UTC, samuelecalamita commented on src/components/toast.ts
> +    return html`<div class="toast">${this.message}</div>`;
schau bitte ob das markup mehr a11y sein kann...

2024-02-26 08:15 UTC, samuelecalamita commented on src/components/toast.ts
> +      background-color: #ffffff;
kann man nicht mit scss variabeln arbeiten?

2024-02-26 08:17 UTC, samuelecalamita commented on src/main.ts
> +import './components/toast.ts';
wäre nicht besser dynamic importiert in den Komponenten die tatsächlich einen toast verwenden?

2024-02-26 08:19 UTC, samuelecalamita commented on src/styles/sass/components/_icons.scss
> +    cursor: pointer;
ich denke hier reicht cursor und padding styles....

2024-02-26 08:20 UTC, samuelecalamita commented on src/styles/sass/components/_icons.scss
> +    border-radius: 4px;
icon label wird nicht gerendert

2024-02-26 10:50 UTC, LoomingEcho commented on src/blocks/icon-overview/icon-overview.ts
> +    <div class="icon-container">
Leider verstehe ich das nicht genau was du meinst könnten wenn du zeit hast mal drüber schauen.

2024-02-26 10:51 UTC, LoomingEcho commented on src/blocks/icon-overview/icon-overview.ts
> +const getMessage = (block: HTMLElement) => {
Kann ich hinzufügen dann braucht man es nicht aus dem Kontext ziehen.

2024-02-26 10:53 UTC, LoomingEcho commented on src/blocks/icon-overview/icon-overview.ts
> +}
Oh das wusste ich nicht. Danke für den hinweiß, vlt solltem an den ordner aus dem git entfernen.
Könnte es in meinem commit mit hinzufügen

2024-02-26 12:37 UTC, LoomingEcho commented on __template__/generic.html
> +									<ul class="iconOverview">
War nicht beabsichtigt. Ich schau mal in der history woran das lag ums in Zukunft zu verhindern

2024-02-27 15:16 UTC, samuelecalamita requested changes
![Screenshot 2024-02-27 at 16 15 36](https://github.com/ifahrentholz/eds-editorial/assets/16286250/0ed235b1-499e-487e-88c5-1a5df9d6ef2c)

bitte überprüfen

2024-02-27 15:16 UTC, samuelecalamita commented on constants.ts
> +export const ICON_PATH = '/public/icons';
bitte das in dem src folder

2024-02-28 16:02 UTC, LoomingEcho commented
Nach dem merge von devleop und den anpassungen die dadruch nötig waren wirft der toast ein error im log aber funcktioneirt rein optisch richtig. Würde das gerne morgen mit dir zusammen anschauen @samuelecalamita

2024-03-04 14:05 UTC, samuelecalamita approved these changes

2024-03-04 14:05 UTC, merged