34 jsdocstypes for utils
ifahrentholz/eds-editorial pull request #41
Opened 2024-02-22 16:46 UTC by LoomingEcho

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #34 

Test URLs:

- Before: https://develop--eds-editorial--ifahrentholz.hlx.live/
- After: https://34-jsdocstypes-for-utils--eds-editorial--ifahrentholz.hlx.live/

2024-02-24 21:18 UTC, samuelecalamita requested changes
Um sicher zu gehen dass die docs auch richtig sind, würde ich sinnvoll finden unit tests für die helpers zu schreiben. Was sagt ihr @ifahrentholz @LoomingEcho ???

2024-02-24 21:18 UTC, samuelecalamita commented on src/utils/getMetadata.ts
> +export function getMetadata(name: string, doc: Document = document): string {
ich würde value besser finden als name

2024-02-24 21:18 UTC, samuelecalamita commented on src/utils/replaceBySpecifier.ts
> +  * // Output: 'This is a <strong>test</strong> string with some <strong>test</strong> keywords.'
bitte nochmal prüfen ob das output example korrrekt ist

2024-02-26 07:21 UTC, LoomingEcho commented
> Um sicher zu gehen dass die docs auch richtig sind, würde ich sinnvoll finden unit tests für die helpers zu schreiben. Was sagt ihr @ifahrentholz @LoomingEcho ???

Könnte sinnvoll sein, in den FAQs wurde auch nach unit tests gefragt, aber wir sollten das eventuell in Mehre tasks aufsplitten. zb. einen um ein test framework (jest, etc ) einzubinden und dann eins um die test zu erstellen.

2024-02-26 08:19 UTC, LoomingEcho commented on src/utils/createOptimizedPicture.ts
> + *   height: 'auto',
Wäre es dann nicht besser in dem Interface number anstelle von string zu erwarten.
zur zeit wird die createOptimisePicture an zwei stellen verwendet wo man eine leicht eine Number anstelle von string verwenden könnte. Das würde die Verwendung der function weniger fehleranfällig machen

2024-02-26 08:31 UTC, LoomingEcho commented on src/utils/createOptimizedPicture.ts
>    breakpoints?: Array<Record<string, string>>;
Ich erstelle eine neues Interface dafür

2024-02-27 10:45 UTC, merged