53 setup unit test with jest
ifahrentholz/eds-editorial pull request #61
Opened 2024-03-04 17:47 UTC by LoomingEcho

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #53

Test URLs:

- Before: https://develop--eds-editorial--ifahrentholz.hlx.live/
- After: https:/53-setup-unit-test-with-jest--eds-editorial--ifahrentholz.hlx.live/

2024-03-04 17:48 UTC, LoomingEcho commented
- [ ] Add step to CI

2024-03-07 09:44 UTC, samuelecalamita requested changes

2024-03-07 09:44 UTC, samuelecalamita commented on .github/workflows/main.yaml
> +      - name: Run Jest tests
Run unit tests

2024-03-07 09:44 UTC, samuelecalamita commented on jest.config.ts
> +const config: Config = {
wie haben schon eine config object. Ich würde das lieber jestConfig nennen...

2024-03-07 09:44 UTC, samuelecalamita commented on jest.config.ts
> +  moduleFileExtensions: ['js', 'ts', 'tsx'],
ich denke tsx brauchen wir nicht

2024-03-07 09:44 UTC, samuelecalamita commented on src/utils/createOptimizedPicture.spec.ts
> +    const pictureElement = createOptimizedPicture(args)!;
was ist "!" ?

2024-03-07 09:44 UTC, samuelecalamita commented on src/utils/replaceBySpecifier.spec.ts
> +
im header benutzten wir replaceBySpecifier so:

```replaceBySpecifier({ input: leftCol.logoText, htmlTag: 'strong', specifier: ':::' });```

bitte auch so ein test schreiben

2024-03-07 09:44 UTC, samuelecalamita commented on src/utils/toCamelCase.spec.ts
> +  test('handles already camelCase string with underscore', () => {
with snake_case

2024-03-07 09:44 UTC, samuelecalamita commented on src/utils/toClassName.spec.ts
> +});
die Datei heißt toClassName und testest toCamelCase nochmal...Falscher copy paste? ;)

2024-03-07 15:31 UTC, LoomingEcho commented on src/utils/createOptimizedPicture.spec.ts
> +    const pictureElement = createOptimizedPicture(args)!;
Versichert das der return kein undefined ist

2024-03-07 15:32 UTC, LoomingEcho commented on src/utils/toCamelCase.spec.ts
> +  test('handles already camelCase string with underscore', () => {
with underscrore ist allgemiener da es auch ein test-string_mit Underscrore sein kann

2024-03-07 15:34 UTC, LoomingEcho commented on src/utils/toClassName.spec.ts
> +});
Ja da hatte ich die basis nicht geändert und weil die namen so änlich sind ist es mir wohl aufgefallen .
Danke für den find

2024-03-07 15:35 UTC, LoomingEcho commented on .github/workflows/main.yaml
> +      - name: Run Jest tests
ok

2024-03-07 15:44 UTC, LoomingEcho commented on src/utils/replaceBySpecifier.spec.ts
> +
ok

2024-03-07 15:44 UTC, LoomingEcho commented on jest.config.ts
> +  moduleFileExtensions: ['js', 'ts', 'tsx'],
ok

2024-03-07 15:45 UTC, LoomingEcho commented on jest.config.ts
> +const config: Config = {
da es ein export default ist spielt es keine rolle aber kann ich gerne machen ist kaum ein aufwand.

2024-03-12 07:28 UTC, samuelecalamita requested changes
bitte für utils/extractSidekickLibraryId.ts löschen, und Tests für wrap.ts schreiben

2024-03-18 12:13 UTC, merged