Test/iza
ifahrentholz/eds-editorial pull request #8
Opened 2024-02-09 07:57 UTC by iza17hor

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-02-19 15:36 UTC, eKrausedivae commented on src/blocks/table/table.ts
> +  const headers = Array.from(tableData.querySelectorAll('div')).map((cell) => cell.innerText);
Ein bisschen kompliziert, ich würde einfach durch die block children durchlaufen:
[...block.children].forEach((child, index) => { } 
und dann durch die children von child: [...child.children].forEach((col) => { }
Wenn index == 0 im header Array speichern, ansonsten im row Array

2024-02-19 15:36 UTC, eKrausedivae commented on src/blocks/table/table.ts
> +  const tableData = block.querySelector('.table div');
Hier wird nur der erste div wiedergegeben

2024-02-19 15:36 UTC, eKrausedivae commented on src/blocks/table/table.ts
> +  if (!tableData) {
diese überprüfung ist glaub ich überflüssig, wenn du ein loop weiter untern verwendest

2024-02-19 15:36 UTC, eKrausedivae commented on src/blocks/table/table.ts
> +  const rows = Array.from(tableData.parentElement?.children || []).filter((row) => row !== tableData);
Anstatt Array.from(tableData) kannst du [...tableData] verwenden

2024-02-21 11:24 UTC, samuelecalamita requested changes

2024-02-21 11:24 UTC, samuelecalamita commented on src/blocks/form/form.ts
> +  render(template(formData), block);
hier renderst du die webcomponent mit dem formLink

2024-02-21 11:24 UTC, samuelecalamita commented on src/blocks/table/table.ts
> +  const data: string[][] = [];
die types für headers und data sollten keine strings sein denke ich. Ein redakteur könnte auch strong oder italic verwenden und wenn wir strings haben dann gehen die styles verloren

2024-02-21 11:24 UTC, samuelecalamita commented on src/blocks/table/table.ts
> +      headers.push(...Array.from(child.querySelectorAll('div')).map((cell) => cell.innerText));
hier wäre dann innerText nicht mehr sinnvoll

2024-02-21 11:24 UTC, samuelecalamita commented on tsconfig.json
> +  "include": ["blocks/**/*.ts", "scripts/**/*.ts", "src/**/*.ts", "src/blocks/table/table.ts"],
ich denke "src/blocks/table/table.ts" ist nicht notwendig

2024-02-27 10:38 UTC, samuelecalamita requested changes
Schau bitte auch: 
* Fehler beim absenden des forms in der console e.reset() function
* wenn das formular geladen wird sieht man kurz die url wo die json verlinkt ist. Kriegen wir das weg?

2024-02-27 10:38 UTC, samuelecalamita commented on src/components/form/form.ts
> +      <div>
wenn das leere div nicht gebraucht wird bitte entfernen. Wenn styles gebraucht werden dann mit einer klasse

2024-02-27 10:38 UTC, samuelecalamita commented on src/blocks/table/table.ts
> +                ${row.map((cell) => html`<td style="${cell.styles || ''}">${cell.text}</td>`)}
hier bitte prüfen wenn man redaktionell strong italic usw. in einem table cell verwendet auch gerendert werden...

2024-02-28 10:51 UTC, eKrausedivae commented
Der reset() Fehler taucht bei mir nicht auf, hattest du vielleicht eine alte Version? Den Rest hab ich gefixed.

2024-03-01 12:27 UTC, samuelecalamita commented
can be merged when #31 is on develop

2024-03-01 13:22 UTC, merged